# Generated by Django 2.0.1 on 2019-08-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_catetypeentity_fruitentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEntity',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='店号')),
                ('name', models.CharField(max_length=50, verbose_name='水果商店名')),
                ('store_type', models.CharField(choices=[(0, '自营'), (1, '第三方')], db_column='type_', max_length=10, verbose_name='类型')),
                ('boss_name', models.CharField(max_length=20, verbose_name='负责人')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('address', models.CharField(max_length=100, verbose_name='商店地址')),
                ('city', models.CharField(db_index=True, max_length=20, verbose_name='所在城市')),
                ('lat', models.FloatField(max_length=20, verbose_name='纬度')),
                ('lon', models.FloatField(max_length=20, verbose_name='经度')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='成立时间')),
                ('last_time', models.DateField(auto_now=True, verbose_name='最后变更时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='catetypeentity',
            options={'ordering': ['-order_num'], 'verbose_name': '水果分类', 'verbose_name_plural': '水果分类'},
        ),
    ]
