# Generated by Django 2.0.1 on 2019-08-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190827_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeentity',
            options={'verbose_name': '水果店', 'verbose_name_plural': '水果店'},
        ),
        migrations.AlterUniqueTogether(
            name='storeentity',
            unique_together={('name', 'city')},
        ),
        migrations.AlterModelTable(
            name='storeentity',
            table='t_store',
        ),
    ]
