# Generated by Django 2.2.4 on 2019-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190827_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='name_photo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='imags', verbose_name='photo', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='photo_height',
            field=models.IntegerField(null=True, verbose_name='LOGO高'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='photo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
    ]
