# Generated by Django 2.2.4 on 2019-08-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190828_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitentity',
            name='name_photo',
            field=models.ImageField(blank=True, height_field='photo_height', null=True, upload_to='imags', verbose_name='photo', width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='photo_height',
            field=models.IntegerField(null=True, verbose_name='photo高'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='photo_width',
            field=models.IntegerField(null=True, verbose_name='photo宽'),
        ),
        migrations.CreateModel(
            name='RealProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('real_type', models.CharField(choices=[(0, '身份证'), (1, '护照'), (2, '驾驶证')], max_length=10)),
                ('number', models.CharField(max_length=30, verbose_name='证件号')),
                ('image1', models.ImageField(upload_to='user/real', verbose_name='正面照')),
                ('image2', models.ImageField(upload_to='user/real', verbose_name='反面照')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='登陆账号')),
            ],
            options={
                'verbose_name': '实名认证表',
                'verbose_name_plural': '实名认证表',
                'db_table': 't_profile',
            },
        ),
    ]
