# Generated by Django 2.2.4 on 2019-08-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190828_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEntity',
            fields=[
                ('no', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='序号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='账号')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 't_cart',
            },
        ),
    ]
