# Generated by Django 2.2.4 on 2019-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190828_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftuitcartentity',
            name='price',
            field=models.IntegerField(null=True, verbose_name='小计'),
        ),
    ]
