# Generated by Django 2.2.4 on 2019-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_ftuitcartentity_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftuitcartentity',
            name='price',
        ),
    ]
