# Generated by Django 2.2.4 on 2019-08-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_ftuitcartentity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(db_table='t_collect', related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
    ]
