# Generated by Django 2.2.4 on 2019-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190829_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='passwd',
            field=models.CharField(default=1, max_length=100, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realprofile',
            name='real_type',
            field=models.CharField(choices=[('0', '身份证'), ('1', '护照'), ('2', '驾驶证')], max_length=10),
        ),
    ]
