# Generated by Django 2.2.4 on 2019-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190831_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentity',
            name='no',
        ),
        migrations.AddField(
            model_name='cartentity',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
