# Generated by Django 2.2.4 on 2019-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190902_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentity',
            name='id',
        ),
        migrations.AddField(
            model_name='cartentity',
            name='no',
            field=models.CharField(default=1, max_length=5, primary_key=True, serialize=False, verbose_name='购物车编号'),
            preserve_default=False,
        ),
    ]
