# Generated by Django 2.2.4 on 2019-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190902_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentity',
            name='no',
            field=models.CharField(auto_created=True, max_length=5, primary_key=True, serialize=False, verbose_name='购物车编号'),
        ),
    ]
