# Generated by Django 2.2.4 on 2019-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20190902_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentity',
            name='no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='购物车编号'),
        ),
    ]
