# Generated by Django 2.2.4 on 2019-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '余额'), (1, '银行卡'), (2, '支付宝'), (3, '微信')], default=0, verbose_name='支付方式'),
        ),
    ]
