# Generated by Django 2.2.4 on 2019-08-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_ftuitcartentity_price'),
        ('orderapp', '0003_ordermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='用户电话')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='OrderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cnt', models.IntegerField(default=1, verbose_name='数量')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='商品id')),
                ('num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 't_orderprofile',
            },
        ),
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单号')),
                ('title', models.CharField(max_length=100, verbose_name='订单名称')),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderapp.AddressEntity', verbose_name='地址id')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '订单管理表',
                'verbose_name_plural': '订单管理表',
                'db_table': 't_order1',
            },
        ),
    ]
