# Generated by Django 2.2.4 on 2019-08-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_auto_20190828_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
