# Generated by Django 2.2.4 on 2019-08-31 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190831_1143'),
        ('orderapp', '0007_delete_ordermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShouCangEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='水果id')),
                ('user_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
                'db_table': 't_shoucang',
            },
        ),
    ]
